version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  api:
    build:
      context: ./microservices
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./microservices:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
