version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build: ./microservices
    ports:
      - "3000:3000"
    volumes:
      - ./microservices:/app
      - /app/node_modules
